### ISSUE TITLE
'IRouteBuilder' does not contain a definition for 'MapSpaFallbackRoute'

### ISSUE THREAD

**Issue by peter-bozovic** [brunolau/BrunoLau.SpaServices#4]
Getting this error after trying to upgrade my project to dotnet 7 & SpaServices v6.0.3:

error CS1061: 'IRouteBuilder' does not contain a definition for 'MapSpaFallbackRoute' and no accessible extension method 'MapSpaFallbackRoute' accepting a first argument of type 'IRouteBuilder' could be found (are you missing a using directive or an assembly reference?)

Everything still seem to work with v0.8.0, but thought that getting into latest version would be better :)
